# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014a8a15e2ea7fd518a6d1de18546b120c2de52484c774d7878766c85764e2ec1be80d5c61903d664e6155834871054ad67354c031c416aa3230ee7b03de484b

test:
  secret_key_base: f7b3cde9fb87430445b6212e297a56eedd3b665772d25f546c109a6a23fd5c1b1b7edee834263bc89caf9cf50f951fbba88203be7a1efdda17be20bdcd1f31c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
